### ISSUE TITLE
no valid values warning

### ISSUE THREAD

**Issue by espher1987** [nset-ornl/wbstats#18]
Hello, first, thanks for this amazing package, i'm getting this problem. I'm trying to get information about:
Export unit value index (2000 = 100)

When i try to get information and save it to a data frame called "df":

````
df <- wb(country = "NI",
         indicator = "TX.UVI.MRCH.XD.WD")
````

i get this message:
````
# Error in wb(country = "NI", indicator = "TX.UVI.MRCH.XD.WD") : 
# indicator parameter has no valid values. Please check documentation for valid inputs
````
This only happen with this kind of index:
TX.UVI.MRCH.XD.WD or TM.UVI.MRCH.XD.WD
but if i try something like:

````
df <- wb(country = "countries_only",
         indicator = "NY.GDP.MKTP.CD")
````
i get no errors.

Thanks in advance.

wbstats Version 0.2
R 3.5.2

PD: Sorry for my English!.

**Comment by jpiburn** [comment]
Hi sorry for the delay on replying. I am thinking that this is probably happening because the cached version of which indicators are available for download that you are using `wb_cachelist` (comes with the `wbstats` package) is out of date and should be updated. I tried the code below just now and it was successful. For more detailed information about this topic you can reference the vignette [here](https://cran.r-project.org/web/packages/wbstats/vignettes/Using_the_wbstats_package.html)

```
library(wbstats)

wb_cache <- wbcache()

df <- wb(country = "NI",
         indicator = "TX.UVI.MRCH.XD.WD", 
         cache = wb_cache)
```
Let me know if this works for you.

**Comment by espher1987** [comment]
Hi, i just try it, thanks. This works great. Now i get the importance of wbcache(). Thank you really much. i love this package and its an amazing solution for data analysis.

pd: sorry for my english.

**Comment by jpiburn** [comment]
great, glad everything is working for you now. If anything else comes up just let me know.

Also... your english is great, no need to apologize :)
